djangofundamentals/blog/urls.py
from django.conf.urls import url
from . import views, views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),
    
    url(r'^comments/$', views.comment_list, name='comment_list'),

    url(r'^cbv/$', views_cbv.post_list, name='post_list_cbv'),
    url(r'^cbv/(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail_cbv'),
    url(r'^cbv/new/$', views_cbv.post_new, name='post_new_cbv'),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name='post_edit_cbv'),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name='post_delete_cbv'),    
]

djangofundamentals/djangofundamentals/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect

def root(request):
    return redirect('blog:post_list')


urlpatterns = [
    # url(r'^$', root, name='root'),
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')), # 위의 기본 accounts를 삭제하지 않고!! 그냥 부가해야함
    # django.contrib.auth 앱 내에서는 namespace를 쓰지 않는 것으로 이미 구현이 되어있으므로
    # accounts 앱에는 namespace를 절대 적용하지 않음!
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    # namespace 넣는 위치에 주의. include 내부임
]

# DEBUG = True 일 때, 개발환경에서 MEDIA를 MEDIA_URL 통해 접근토록 도와주는 코드
# DEBUG = False이면 아래 코드는 빈 리스트 리턴
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

djangofundamentals/blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.

import re
from django.forms import ValidationError
# validation function은 value 하나를 인자로 받으며,
# return 값이 아니라 오류가 있을 경우 raise Error가 필요한 형태
def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+.?\d*),\s?([+-]?\d+.?\d*)$', value):  #\s?는 띄어쓰기가 0 또는 1개 있음을 의미
        raise ValidationError('Invalid lnglat')

from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'draft'),
        ('p', 'published'),
        ('w', 'withdrawn'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_post_set')
    title = models.CharField(max_length=100, verbose_name='제목', help_text='100자 이내로 제목을 적어주세요')  # 길이제한이 있는 문자열
    content = models.TextField(verbose_name="내용")   # 길이제한이 없는 문자열. DB를 위한 구분
    photo = ProcessedImageField(blank=True,
        upload_to="blog/post/%Y/%m/%d",   # 앞뒤로 슬래시 없어야함! 
        processors=[Thumbnail(300,300)],
        format='jpeg',   # 확장자는 .jpg 로 저장됨
        options={'quality':70}            
    )
    tags = models.CharField(max_length=100, blank=True)
    tag_set = models.ManyToManyField('Tag', blank=True)   # Tag를 문자열로 감싸서 넣어줄 것. 그래야 undefined 에러 피할 수 있음
    # ManyToManyField의 필드명은 '_set'으로 하는 것을 권장 
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    lnglat = models.CharField(max_length=50, blank=True,     # lng(경도), lat(위도) 순서
        validators=[lnglat_validator],
        help_text='경도,위도 포맷으로 입력')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    # __str__과 같은 함수는 DB의 칼럼에 반영되지 않으므로 migration 불필요함
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

    # 특정 모델에 대한 Detail뷰를 작성이 필요한 경우, 모델 클래스의 함수로 get_absolute_url 정의하면 아주 편해짐
    # resolve_url(post) 로 사용하면 바로 가장 먼저 체크되는 hasattr(post, 'get_absolute_url') 에 걸려서
    # 그 함수의 리턴값인 detail뷰의 url string을 리턴받게 됨


class Comment(models.Model):
    post = models.ForeignKey(Post)   # 'Post'로 넣어줘도 좋음.
    # DB 상에는 post_id 를 이름으로 하는 컬럼이 생성됨!!
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

djangofundamentals/blog/forms.py
from django import forms
from .models import Post
from djangofundamentals.widgets.naver_map_point_widget import NaverMapPointWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # fields = ['title', 'content', 'tag_set', 'status', 'lnglat']
        widgets = {
            'lnglat': NaverMapPointWidget(attrs={'width':600, 'height':300}),
        }

djangofundamentals/blog/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

def post_list(request):
    qs = Post.objects.all().select_related('user').prefetch_related('comment_set', 'tag_set')
    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__icontains=q)

    return render(request, 'blog/post_list.html', {
        'post_list':qs,
        'q':q,
    })

from django.http import Http404
from django.shortcuts import get_object_or_404

def post_detail(request, id):
    # post = Post.objects.get(id=id)  
    # 이 경우 게시물 미존재 시 http 500 코드를 응답하는 문제

    # try:
    #     post = Post.objects.get(id=id)
    # except (Post.DoesNotExist, Post.MultipleObjectsReturned):
    #     raise Http404
    # 이렇게 매번 try 구문 쓰는 번거로움을 피하기 위해 get_object_or_404 사용

    post = get_object_or_404(Post, id=id)  # 추천. 게시물 미존재 시 404 코드로 응답

    return render(request, 'blog/post_detail.html', {
        'post':post,
    })


from .forms import PostForm
from django.shortcuts import redirect

from django.contrib import messages

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            # Message Framework를 이용하는 방법1(전통)
            # messages.add_message(request, messages.SUCCESS, '새 글이 등록되었습니다!')
            # Message Framework를 이용하는 방법2(shortcut)
            messages.success(request, '새 글이 등록되었습니다!!')
            # message는 redirect 이전에 보내져야 함!
            return redirect(post)    # success_url 아니면 get_absolute_url 경로로 순차적으로 감
    else:
        form = PostForm()
  
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            # messages.error(request, '에러에러')
            messages.success(request, '성공적으로 수정되었습니다')
            return redirect(post)    # success_url 아니면 get_absolute_url 경로로 순차적으로 감
    else:
        form = PostForm(instance=post)
  
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


from .models import Comment

def comment_list(request):
    comment_list = Comment.objects.all().select_related('post')
    return render(request, 'blog/comment_list.html', {'comment_list': comment_list})

djangofundamentals/blog/templates/blog/comment_list.html
{% extends 'blog/layout.html' %}

{% block content %}
<ul>
{% for comment in comment_list  %}
    <li>{{ comment.post }}에 대한 댓글: {{ comment }} , {{ comment.author }} , {{ comment.created_at }}</li>
{% endfor %}
</ul>
{% endblock  %}

djangofundamentals/blog/templates/blog/layout.html
{% extends 'layout.html' %}

{% block title %}Django Fundamentals{% endblock %}
 

djangofundamentals/blog/templates/blog/post_confirm_delete.html
<h1>{{ post }} 삭제 하시겠습니까</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제 진행" />
    <!-- <a href="{% url 'blog:post_detail' post.id %}">아니오</a> -->
    <a href="{{ post.get_absolute_url }}">아니오</a> 
</form>

djangofundamentals/blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %}
{% load imagekit %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>
                <!-- <img src="/media/{{ post.photo }}" style="max-width: 100%" /> 비추천 -->
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" style="max-width: 100%" /> <!-- 추천 -->
                    {% thumbnail "100x100" post.photo %}
                    {% thumbnail "100x100" post.photo as thumb %}
                    <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />
                    {% thumbnail "100x100" post.photo -- style="" onclick="" class="" %}
                {% endif %}
                <small>{{ post.author }}</small>
                <div>{{ post.content|linebreaks }}</div>
            
                <hr/>
            
                <h3>Comments</h3>
                <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>{{ comment.author }}</small>
                        <small>{{ comment.created_at }}</small>
                    </li>
                {% endfor %}
                </ul>
            
                <hr/>
                <p>
                    <a class="btn btn-primary" href="{% url 'blog:post_list' %}">글 목록</a>
                    <a class="btn btn-default" href="{% url 'blog:post_edit' post.id %}">글 수정</a>
                </p>
            </div>
        </div>
    </div>


{% endblock %}

djangofundamentals/blog/templates/blog/post_form.html
{% extends 'blog/layout.html' %}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
<input type="submit">
</form>        

{% endblock %}

djangofundamentals/blog/templates/blog/post_list.html
{% extends 'blog/layout.html' %}


{% block content %}


<div class="container">    
    <div class="jumbotron">         
        <h1>Django Fundamentals<sup>by pitachips</sup></h1>         
        <p>장고 기본부터 착실히</p>       
        <p><a class="btn btn-lg btn-primary" href="http://github.com/pitachips">pitachips Github &raquo;</a></p>     
    </div>  

    <div class="row">
        <div class="col-sm-12">
            <a href="{% url 'blog:post_new' %}" class="btn btn-primary pull-right">새글 쓰기</a>
            <p>
                <form action="" method="GET">
                    <input type="text" name="q" value={{q}}>
                    <input class="btn btn-primary" type="submit" value="검색"> 
                </form>
            </p>
            <table class="table table-hover tabler-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in post_list %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td>
                            <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                            {% for tag in post.tag_set.all %}
                                <span class="label label-info">{{ tag.name }}</span>
                            {% endfor %}
                        </td>
                        <td><small>by {{ post.user }}</small></td>
                        <td><small>at {{ post.updated_at }}</small></td>
                        <!-- <td>{{ post.comment_set.all }}</td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


</div>


{% endblock %}